//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("WildGums")]
[assembly: AssemblyVersion("6.0.3")]
[assembly: AssemblyFileVersion("6.0.3")]
[assembly: AssemblyInformationalVersion("6.0.3")]
[assembly: AssemblyCopyright("Copyright © WildGums 2010 - 2018")]

